const BIG_SCREEN_SIZE = 1220;
const SMALL_SCREEN_SIZE = 760;
const CARDS_QUANTITY_DESKTOP = 12;
const CARDS_QUANTITY_TABLET = 8;
const CARDS_QUANTITY_MOBILE = 5;
const CARDS_MORE_DESKTOP = 3;
const CARDS_MORE_MOBILE = 2;
const SHORT_MOVIES_DURATION = 40;

export {
  BIG_SCREEN_SIZE,
  SMALL_SCREEN_SIZE,
  CARDS_QUANTITY_DESKTOP,
  CARDS_QUANTITY_TABLET,
  CARDS_QUANTITY_MOBILE,
  CARDS_MORE_DESKTOP,
  CARDS_MORE_MOBILE,
  SHORT_MOVIES_DURATION,
};
